<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>mu.nu.nullpo</groupId>
		<artifactId>nullpomino</artifactId>
		<version>7.6.0-SNAPSHOT</version>
	</parent>
	
	<artifactId>nullpomino-run</artifactId>
	<packaging>pom</packaging>
	
	<dependencies>
		<dependency>
			<groupId>mu.nu.nullpo</groupId>
			<artifactId>nullpomino-netplay</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>mu.nu.nullpo</groupId>
			<artifactId>nullpomino-modes</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>mu.nu.nullpo</groupId>
			<artifactId>nullpomino-swing</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>mu.nu.nullpo</groupId>
			<artifactId>nullpomino-slick</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>mu.nu.nullpo</groupId>
			<artifactId>nullpomino-tools</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>workingdir-config</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/install/config</outputDirectory>
							<resources>
								<resource>
									<directory>config</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
					<execution>
						<id>workingdir-doc</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/install/doc</outputDirectory>
							<resources>
								<resource>
									<directory>doc</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
					<execution>
						<id>workingdir-res</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/install/res</outputDirectory>
							<resources>
								<resource>
									<directory>res</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
					<execution>
						<id>workingdir-scripts</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/install</outputDirectory>
							<resources>
								<resource>
									<directory>scripts</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.11.0</version>
				<executions>
					<execution>
						<id>lib-jars</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<!-- excludeArtifactIds>nullpomino-core</excludeArtifactIds-->
							<outputDirectory>${project.build.directory}/install/lib</outputDirectory>
							<overWriteIfNewer>true</overWriteIfNewer>
							<overWriteReleases>true</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>
							<stripVersion>true</stripVersion>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin> 
				<groupId>com.googlecode.mavennatives</groupId>
				<artifactId>maven-nativedependencies-plugin</artifactId>
				<version>0.0.7</version>
				<configuration>
					<nativesTargetDir>${project.build.directory}/install/lib</nativesTargetDir>
					<separateDirs>false</separateDirs>
				</configuration>
				<executions>
					<execution>
						<id>unpacknatives</id>
						<goals>
							<goal>copy</goal>
						</goals>
					</execution> 
				</executions> 
			</plugin>
		</plugins>
	</build>
</project>