<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>mu.nu.nullpo</groupId>
	<artifactId>nullpomino</artifactId>
	<version>7.6.0-SNAPSHOT</version>
	
	<packaging>pom</packaging>

	<modules>
		<module>nullpomino-core</module>
		<module>nullpomino-netplay</module>
		<module>nullpomino-modes</module>
		<module>nullpomino-swing</module>
		<module>nullpomino-slick</module>
		<module>nullpomino-tools</module>
		<module>nullpomino-run</module>
	</modules>
	
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<lombok.version>1.18.46</lombok.version>
		<junit.version>6.1.0</junit.version>
		<jinput.version>2.0.10</jinput.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>${junit.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>ch.qos.reload4j</groupId>
				<artifactId>reload4j</artifactId>
				<version>1.2.26</version>
			</dependency>
			<dependency>
				<groupId>org.slick2d</groupId>
				<artifactId>slick2d-core</artifactId>
				<version>1.0.2</version>
				<exclusions>
					<exclusion>
						<groupId>javax.jnlp</groupId>
						<artifactId>jnlp-api</artifactId>
					</exclusion>
					<exclusion>
						<groupId>org.lwjgl.lwjgl</groupId>
						<artifactId>lwjgl</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.jmonkeyengine</groupId>
				<artifactId>lwjgl</artifactId>
				<version>2.9.5</version>
			</dependency>
			<dependency>
				<groupId>net.java.jinput</groupId>
				<artifactId>jinput</artifactId>
				<version>${jinput.version}</version>
			</dependency>
			<dependency>
				<groupId>net.java.jinput</groupId>
				<artifactId>jinput</artifactId>
				<version>${jinput.version}</version>
				<classifier>natives-all</classifier>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.15.0</version>
					<configuration>
						<source>25</source>
						<target>25</target>
						<encoding>UTF-8</encoding>
						<annotationProcessorPaths>
							<path>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
								<version>${lombok.version}</version>
							</path>
						</annotationProcessorPaths>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>3.6.3</version>
					<executions>
						<execution>
							<id>enforce-maven</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<configuration>
								<rules>
									<requireMavenVersion>
										<version>3.9.10</version>
									</requireMavenVersion>
								</rules>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.5.0</version>
					<configuration>
						<encoding>UTF-8</encoding>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<version>2.21.0</version>
					<configuration>
						<processDependencyManagementTransitive>false</processDependencyManagementTransitive>
						<!-- exclude non-relese versions -->
						<ignoredVersions>.*-M.*,.*-(alpha|beta).*</ignoredVersions>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.sonarsource.scanner.maven</groupId>
					<artifactId>sonar-maven-plugin</artifactId>
					<version>5.7.0.6970</version>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>